### ISSUE TITLE
"npx create-ink-app --typescript" fails to install deps

### ISSUE THREAD

**Issue by shogunsea** [vadimdemedes/create-ink-app#33]
```
❯ npx create-ink-app --typescript

  ✔ Copy files
  ✖ Install dependencies
    → npm ERR!     XXXX.npm/_logs/2023-06-30T18_29_32_345Z-debug.log
    Format code
    Build
    Link executable
Error: Command failed with exit code 254: npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ava@5.3.1',
npm WARN EBADENGINE   required: { node: '>=14.19 <15 || >=16.15 <17 || >=18' },
npm WARN EBADENGINE   current: { node: 'v16.10.0', npm: '7.24.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'write-file-atomic@5.0.1',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.10.0', npm: '7.24.0' }
npm WARN EBADENGINE }
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path XXXXcode/test-ink/node_modules/xo/node_modules/typescript/bin/tsc
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod 'XXXXcode/test-ink/node_modules/xo/node_modules/typescript/bin/tsc'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     XXXX.npm/_logs/2023-06-30T18_29_32_345Z-debug.log
    at makeError (file://XXXX.npm/_npx/cc9fa0209c2baa81/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file://XXXX.npm/_npx/cc9fa0209c2baa81/node_modules/execa/index.js:124:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Task.task (file://XXXX.npm/_npx/cc9fa0209c2baa81/node_modules/create-ink-app/index.js:148:6)```

**Comment by shogunsea** [comment]
ah nvm it's the node version issue
